#!/usr/bin/env bash
set -euo pipefail

# [generated by initializer agent - edit as needed]

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

HOST="${ATP_DEV_HOST:-127.0.0.1}"
PORT="${ATP_DEV_PORT:-3000}"
BASE_URL="http://${HOST}:${PORT}"
PID_FILE="${ROOT_DIR}/.devserver.pid"
LOG_FILE="${ROOT_DIR}/.devserver.log"

# Placeholder development configuration. Replace these with real values in the
# deployment environment; do not commit secrets.
export ATP_ENV="${ATP_ENV:-development}"
export ATP_IB_HOST="${ATP_IB_HOST:-127.0.0.1}"
export ATP_IB_LIVE_PORT="${ATP_IB_LIVE_PORT:-4001}"
export ATP_IB_PAPER_PORT="${ATP_IB_PAPER_PORT:-4002}"
export ATP_MARKET_DATA_LINE_LIMIT="${ATP_MARKET_DATA_LINE_LIMIT:-100}"
export ATP_SSD_DATA_DIR="${ATP_SSD_DATA_DIR:-${ROOT_DIR}/data/ssd}"
export ATP_NAS_DATA_DIR="${ATP_NAS_DATA_DIR:-${ROOT_DIR}/data/nas}"
export ATP_SMTP_API_KEY="${ATP_SMTP_API_KEY:-placeholder-set-in-environment}"
export ATP_SMS_API_KEY="${ATP_SMS_API_KEY:-placeholder-set-in-environment}"
export DATABENTO_API_KEY="${DATABENTO_API_KEY:-placeholder-set-in-environment}"
export SHARADAR_API_KEY="${SHARADAR_API_KEY:-placeholder-set-in-environment}"

# SRS-SDK-006: pandas-ta pulls in numba transitively. Numba's JIT path is
# irrelevant to the SDK code paths (only pandas_ta.sma + pandas_ta.bbands
# are called, both plain pandas / numpy) and can fail at import time on
# edge-case interpreter / LLVM combinations. Disabling the JIT here makes
# the import deterministic across every supported interpreter.
export NUMBA_DISABLE_JIT="${NUMBA_DISABLE_JIT:-1}"

# SRS-ARCH-005 / SRS-ORCH-002 / SyRS SYS-57/58 strategy resource limits.
export ATP_LIVE_STRATEGY_MEM_MB="${ATP_LIVE_STRATEGY_MEM_MB:-512}"
export ATP_LIVE_STRATEGY_CPU="${ATP_LIVE_STRATEGY_CPU:-0.25}"
export ATP_PAPER_STRATEGY_MEM_MB="${ATP_PAPER_STRATEGY_MEM_MB:-300}"
export ATP_PAPER_STRATEGY_CPU="${ATP_PAPER_STRATEGY_CPU:-0.10}"
export ATP_HOST_MEMORY_SAFETY_MARGIN_MB="${ATP_HOST_MEMORY_SAFETY_MARGIN_MB:-2048}"

echo "→ Installing dependencies..."

VENV_DIR="${ROOT_DIR}/.venv"

# SRS-SDK-006: enforce the python/pyproject.toml requires-python window
# (>=3.12,<3.14) on the Python used to build the venv. pandas-ta (via
# numba) does not support 3.14; picking 3.14 here lets pip install fail
# obscurely several steps later. Allow ATP_PYTHON to override the
# discovered interpreter so CI / Docker can pin the exact minor version.
discover_python() {
  if [[ -n "${ATP_PYTHON:-}" ]]; then
    echo "$ATP_PYTHON"
    return
  fi
  for candidate in python3.13 python3.12 python3; do
    if command -v "$candidate" >/dev/null 2>&1; then
      local version
      version=$("$candidate" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")' 2>/dev/null)
      case "$version" in
        3.12|3.13)
          echo "$candidate"
          return
          ;;
      esac
    fi
  done
  echo ""
}

PYTHON_BIN="$(discover_python)"
if [[ -z "$PYTHON_BIN" ]]; then
  echo "✗ Environment failed"
  echo "  No Python interpreter in the supported range 3.12 - 3.13 was found."
  echo "  python/pyproject.toml requires-python = >=3.12,<3.14 (SRS-SDK-006)."
  echo "  Install a supported interpreter or set ATP_PYTHON to one explicitly."
  exit 1
fi

if [[ ! -d "$VENV_DIR" ]]; then
  echo "  Creating Python venv at $VENV_DIR with $PYTHON_BIN..."
  "$PYTHON_BIN" -m venv "$VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
VENV_PY_VERSION=$(python -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")')
if [[ "$VENV_PY_VERSION" != "3.12" && "$VENV_PY_VERSION" != "3.13" ]]; then
  echo "✗ Environment failed"
  echo "  Existing .venv is Python $VENV_PY_VERSION but the project requires >=3.12,<3.14."
  echo "  Remove .venv and re-run, or set ATP_PYTHON to a supported interpreter."
  exit 1
fi
echo "  Using $(python -c 'import sys; print(sys.executable)') (Python $VENV_PY_VERSION)"

python -m pip install --quiet --upgrade pip
if [[ -f requirements.txt ]]; then
  python -m pip install --quiet -r requirements.txt
fi

if [[ -f package.json ]]; then
  npm install
fi

if [[ -f Cargo.toml ]] && command -v cargo >/dev/null 2>&1; then
  cargo fetch
elif [[ -f Cargo.toml ]]; then
  echo "  Cargo.toml found but cargo is not installed; skipping cargo fetch."
fi

server_is_ready() {
  curl -sf "$BASE_URL" >/dev/null 2>&1
}

pid_is_running() {
  [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" >/dev/null 2>&1
}

echo "→ Starting dev server..."
if pid_is_running && server_is_ready; then
  echo "  Dev server already running at $BASE_URL."
elif server_is_ready; then
  echo "  A server is already reachable at $BASE_URL; using it for smoke tests."
else
  rm -f "$PID_FILE"
  : > "$LOG_FILE"
  nohup python3 -m http.server "$PORT" --bind "$HOST" > "$LOG_FILE" 2>&1 &
  SERVER_PID=$!
  disown "$SERVER_PID" >/dev/null 2>&1 || true
  echo "$SERVER_PID" > "$PID_FILE"
  echo "  Started fallback static dev server with PID $SERVER_PID."
fi

echo "→ Waiting for server..."
READY=false
for _ in {1..30}; do
  if server_is_ready; then
    READY=true
    break
  fi
  sleep 1
done

if [[ "$READY" != "true" ]]; then
  echo "✗ Environment failed"
  echo "  Server did not become reachable at $BASE_URL. See $LOG_FILE."
  exit 1
fi

echo "→ Running baseline smoke test..."
if ! curl -sf "$BASE_URL/README.md" >/dev/null; then
  echo "✗ Environment failed"
  exit 1
fi

echo "→ Running REST API contract check..."
if ! python3 tools/rest_api_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  REST API contract check failed; run python3 tools/rest_api_check.py for detail."
  exit 1
fi

echo "→ Running WebSocket API contract check..."
if ! python3 tools/websocket_api_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  WebSocket API contract check failed; run python3 tools/websocket_api_check.py for detail."
  exit 1
fi

echo "→ Running CLI contract check..."
if ! python3 tools/cli_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  CLI contract check failed; run python3 tools/cli_check.py for detail."
  exit 1
fi

echo "→ Running operator workflow surface check..."
if ! python3 tools/operator_workflow_surface_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Operator workflow surface check failed; run python3 tools/operator_workflow_surface_check.py for detail."
  exit 1
fi

echo "→ Running log record contract check..."
if ! python3 tools/log_record_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Log record contract check failed; run python3 tools/log_record_check.py for detail."
  exit 1
fi

echo "→ Running brokerage adapter contract check..."
if ! python3 tools/adapter_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Adapter contract check failed; run python3 tools/adapter_check.py for detail."
  exit 1
fi

echo "→ Running data provider contract check..."
if ! python3 tools/data_provider_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Data provider contract check failed; run python3 tools/data_provider_check.py for detail."
  exit 1
fi

echo "→ Running unified historical data contract check..."
if ! python3 tools/historical_data_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Historical data contract check failed; run python3 tools/historical_data_check.py for detail."
  exit 1
fi

echo "→ Running error handling contract check..."
if ! python3 tools/error_handling_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Error handling contract check failed; run python3 tools/error_handling_check.py for detail."
  exit 1
fi

echo "→ Running connectivity contract check..."
if ! python3 tools/connectivity_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Connectivity contract check failed; run python3 tools/connectivity_check.py for detail."
  exit 1
fi

echo "→ Running freshness contract check..."
if ! python3 tools/freshness_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Freshness contract check failed; run python3 tools/freshness_check.py for detail."
  exit 1
fi

echo "→ Running live-designation contract check..."
if ! python3 tools/live_designation_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Live-designation contract check failed; run python3 tools/live_designation_check.py for detail."
  exit 1
fi

echo "→ Running subscription-limit contract check..."
if ! python3 tools/subscription_limit_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Subscription-limit contract check failed; run python3 tools/subscription_limit_check.py for detail."
  exit 1
fi

echo "→ Running subscription fan-out contract check..."
if ! python3 tools/subscription_fanout_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Subscription fan-out contract check failed; run python3 tools/subscription_fanout_check.py for detail."
  exit 1
fi

echo "→ Running ingestion validation contract check..."
if ! python3 tools/ingestion_validation_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Ingestion validation contract check failed; run python3 tools/ingestion_validation_check.py for detail."
  exit 1
fi

echo "→ Running pacing budget contract check..."
if ! python3 tools/pacing_budget_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Pacing budget contract check failed; run python3 tools/pacing_budget_check.py for detail."
  exit 1
fi

echo "→ Running hot-swap demotion contract check..."
if ! python3 tools/hot_swap_demotion_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Hot-swap demotion contract check failed; run python3 tools/hot_swap_demotion_check.py for detail."
  exit 1
fi

echo "→ Running kill-switch liquidation-timeout contract check..."
if ! python3 tools/kill_switch_timeout_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Kill-switch timeout contract check failed; run python3 tools/kill_switch_timeout_check.py for detail."
  exit 1
fi

echo "→ Running backtest engine contract check..."
if ! python3 tools/backtest_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Backtest engine contract check failed; run python3 tools/backtest_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running backtest cost-model contract check..."
if ! python3 tools/backtest_cost_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Backtest cost-model contract check failed; run python3 tools/backtest_cost_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running backtest determinism contract check..."
if ! python3 tools/determinism_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Backtest determinism contract check failed; run python3 tools/determinism_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running simulation shared-cost-model contract check..."
if ! python3 tools/sim_cost_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Simulation shared-cost-model contract check failed; run python3 tools/sim_cost_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running simulation paper order-intake contract check..."
if ! python3 tools/sim_order_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Simulation paper order-intake contract check failed; run python3 tools/sim_order_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running simulation fill-model contract check..."
if ! python3 tools/sim_fill_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Simulation fill-model contract check failed; run python3 tools/sim_fill_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running simulation virtual-ledger contract check..."
if ! python3 tools/sim_ledger_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Simulation virtual-ledger contract check failed; run python3 tools/sim_ledger_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running simulation paper-state persistence contract check..."
if ! python3 tools/sim_persistence_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Simulation paper-state persistence contract check failed; run python3 tools/sim_persistence_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running performance-metric contract check..."
if ! python3 tools/metrics_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Performance-metric contract check failed; run python3 tools/metrics_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running benchmark-comparison contract check..."
if ! python3 tools/benchmark_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Benchmark-comparison contract check failed; run python3 tools/benchmark_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running backtest-record persistence contract check..."
if ! python3 tools/backtest_store_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Backtest-record persistence contract check failed; run python3 tools/backtest_store_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running factor-analysis contract check..."
if ! python3 tools/factor_analysis_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Factor-analysis contract check failed; run python3 tools/factor_analysis_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running scheduled factor-job contract check..."
if ! python3 tools/factor_job_check.py --require-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Scheduled factor-job contract check failed; run python3 tools/factor_job_check.py --require-cargo for detail."
  exit 1
fi

echo "→ Running orchestrator lifecycle contract check..."
if ! python3 tools/orchestrator_lifecycle_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Orchestrator lifecycle contract check failed; run python3 tools/orchestrator_lifecycle_check.py for detail."
  exit 1
fi

echo "→ Running orchestrator resource-profile contract check..."
if ! python3 tools/orchestrator_resource_profile_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Orchestrator resource-profile contract check failed; run python3 tools/orchestrator_resource_profile_check.py for detail."
  exit 1
fi

echo "→ Running orchestrator workload-priority contract check..."
if ! python3 tools/orchestrator_workload_priority_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Orchestrator workload-priority contract check failed; run python3 tools/orchestrator_workload_priority_check.py for detail."
  exit 1
fi

echo "→ Running orchestrator deployment-version contract check..."
if ! python3 tools/orchestrator_deployment_version_check.py --skip-cargo >/dev/null; then
  echo "✗ Environment failed"
  echo "  Orchestrator deployment-version contract check failed; run python3 tools/orchestrator_deployment_version_check.py for detail."
  exit 1
fi

echo "→ Running Python Strategy API parity contract check..."
if ! python3 tools/strategy_api_parity_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Strategy API parity contract check failed; run python3 tools/strategy_api_parity_check.py for detail."
  exit 1
fi

echo "→ Running Python Strategy API scheduler contract check..."
if ! python3 tools/strategy_api_scheduler_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Strategy API scheduler contract check failed; run python3 tools/strategy_api_scheduler_check.py for detail."
  exit 1
fi

echo "→ Running Python Strategy API subscriptions contract check..."
if ! python3 tools/strategy_api_subscriptions_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Strategy API subscriptions contract check failed; run python3 tools/strategy_api_subscriptions_check.py for detail."
  exit 1
fi

echo "→ Running Python Strategy API order-events contract check..."
if ! python3 tools/strategy_api_order_events_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Strategy API order-events contract check failed; run python3 tools/strategy_api_order_events_check.py for detail."
  exit 1
fi

echo "→ Running Python Strategy API warm-up contract check..."
if ! python3 tools/strategy_api_warmup_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Strategy API warm-up contract check failed; run python3 tools/strategy_api_warmup_check.py for detail."
  exit 1
fi

echo "→ Running Python Strategy API indicators contract check..."
if ! python3 tools/strategy_api_indicators_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Strategy API indicators contract check failed; run python3 tools/strategy_api_indicators_check.py for detail."
  exit 1
fi

echo "→ Running Python Strategy API documentation contract check..."
if ! python3 tools/strategy_api_documentation_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Strategy API documentation contract check failed; run python3 tools/strategy_api_documentation_check.py for detail."
  exit 1
fi

echo "→ Running deployment configuration check..."
if ! python3 tools/deployment_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Deployment check failed; run python3 tools/deployment_check.py for detail."
  exit 1
fi

echo "→ Running configuration system check..."
if ! python3 tools/config_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Configuration check failed; run python3 tools/config_check.py for detail."
  exit 1
fi

echo "→ Running startup readiness gate contract check..."
if ! python3 tools/startup_readiness_gate_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Startup readiness gate check failed; run python3 tools/startup_readiness_gate_check.py for detail."
  exit 1
fi

echo "✓ Environment ready"
