#!/usr/bin/env bash
set -euo pipefail

# [generated by initializer agent - edit as needed]

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

HOST="${ATP_DEV_HOST:-127.0.0.1}"
PORT="${ATP_DEV_PORT:-3000}"
BASE_URL="http://${HOST}:${PORT}"
PID_FILE="${ROOT_DIR}/.devserver.pid"
LOG_FILE="${ROOT_DIR}/.devserver.log"

# Placeholder development configuration. Replace these with real values in the
# deployment environment; do not commit secrets.
export ATP_ENV="${ATP_ENV:-development}"
export ATP_IB_HOST="${ATP_IB_HOST:-127.0.0.1}"
export ATP_IB_LIVE_PORT="${ATP_IB_LIVE_PORT:-4001}"
export ATP_IB_PAPER_PORT="${ATP_IB_PAPER_PORT:-4002}"
export ATP_MARKET_DATA_LINE_LIMIT="${ATP_MARKET_DATA_LINE_LIMIT:-100}"
export ATP_SSD_DATA_DIR="${ATP_SSD_DATA_DIR:-${ROOT_DIR}/data/ssd}"
export ATP_NAS_DATA_DIR="${ATP_NAS_DATA_DIR:-${ROOT_DIR}/data/nas}"
export ATP_SMTP_API_KEY="${ATP_SMTP_API_KEY:-placeholder-set-in-environment}"
export ATP_SMS_API_KEY="${ATP_SMS_API_KEY:-placeholder-set-in-environment}"
export DATABENTO_API_KEY="${DATABENTO_API_KEY:-placeholder-set-in-environment}"
export SHARADAR_API_KEY="${SHARADAR_API_KEY:-placeholder-set-in-environment}"

echo "→ Installing dependencies..."
if [[ -f package.json ]]; then
  npm install
else
  echo "  No package.json found; skipping npm install."
fi

if [[ -f requirements.txt ]]; then
  python3 -m pip install -r requirements.txt
else
  echo "  No requirements.txt found; skipping pip install."
fi

if [[ -f Cargo.toml ]] && command -v cargo >/dev/null 2>&1; then
  cargo fetch
elif [[ -f Cargo.toml ]]; then
  echo "  Cargo.toml found but cargo is not installed; skipping cargo fetch."
else
  echo "  No Cargo.toml found; skipping cargo fetch."
fi

server_is_ready() {
  curl -sf "$BASE_URL" >/dev/null 2>&1
}

pid_is_running() {
  [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" >/dev/null 2>&1
}

echo "→ Starting dev server..."
if pid_is_running && server_is_ready; then
  echo "  Dev server already running at $BASE_URL."
elif server_is_ready; then
  echo "  A server is already reachable at $BASE_URL; using it for smoke tests."
else
  rm -f "$PID_FILE"
  : > "$LOG_FILE"
  nohup python3 -m http.server "$PORT" --bind "$HOST" > "$LOG_FILE" 2>&1 &
  SERVER_PID=$!
  disown "$SERVER_PID" >/dev/null 2>&1 || true
  echo "$SERVER_PID" > "$PID_FILE"
  echo "  Started fallback static dev server with PID $SERVER_PID."
fi

echo "→ Waiting for server..."
READY=false
for _ in {1..30}; do
  if server_is_ready; then
    READY=true
    break
  fi
  sleep 1
done

if [[ "$READY" != "true" ]]; then
  echo "✗ Environment failed"
  echo "  Server did not become reachable at $BASE_URL. See $LOG_FILE."
  exit 1
fi

echo "→ Running baseline smoke test..."
if curl -sf "$BASE_URL/README.md" >/dev/null; then
  echo "✓ Environment ready"
else
  echo "✗ Environment failed"
  exit 1
fi
