#!/usr/bin/env bash
set -euo pipefail

# [generated by initializer agent - edit as needed]

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

HOST="${ATP_DEV_HOST:-127.0.0.1}"
PORT="${ATP_DEV_PORT:-3000}"
BASE_URL="http://${HOST}:${PORT}"
PID_FILE="${ROOT_DIR}/.devserver.pid"
LOG_FILE="${ROOT_DIR}/.devserver.log"

# Placeholder development configuration. Replace these with real values in the
# deployment environment; do not commit secrets.
export ATP_ENV="${ATP_ENV:-development}"
export ATP_IB_HOST="${ATP_IB_HOST:-127.0.0.1}"
export ATP_IB_LIVE_PORT="${ATP_IB_LIVE_PORT:-4001}"
export ATP_IB_PAPER_PORT="${ATP_IB_PAPER_PORT:-4002}"
export ATP_MARKET_DATA_LINE_LIMIT="${ATP_MARKET_DATA_LINE_LIMIT:-100}"
export ATP_SSD_DATA_DIR="${ATP_SSD_DATA_DIR:-${ROOT_DIR}/data/ssd}"
export ATP_NAS_DATA_DIR="${ATP_NAS_DATA_DIR:-${ROOT_DIR}/data/nas}"
export ATP_SMTP_API_KEY="${ATP_SMTP_API_KEY:-placeholder-set-in-environment}"
export ATP_SMS_API_KEY="${ATP_SMS_API_KEY:-placeholder-set-in-environment}"
export DATABENTO_API_KEY="${DATABENTO_API_KEY:-placeholder-set-in-environment}"
export SHARADAR_API_KEY="${SHARADAR_API_KEY:-placeholder-set-in-environment}"

# SRS-ARCH-005 / SRS-ORCH-002 / SyRS SYS-57/58 strategy resource limits.
export ATP_LIVE_STRATEGY_MEM_MB="${ATP_LIVE_STRATEGY_MEM_MB:-512}"
export ATP_LIVE_STRATEGY_CPU="${ATP_LIVE_STRATEGY_CPU:-0.25}"
export ATP_PAPER_STRATEGY_MEM_MB="${ATP_PAPER_STRATEGY_MEM_MB:-300}"
export ATP_PAPER_STRATEGY_CPU="${ATP_PAPER_STRATEGY_CPU:-0.10}"
export ATP_HOST_MEMORY_SAFETY_MARGIN_MB="${ATP_HOST_MEMORY_SAFETY_MARGIN_MB:-2048}"

echo "→ Installing dependencies..."

VENV_DIR="${ROOT_DIR}/.venv"
if [[ ! -d "$VENV_DIR" ]]; then
  echo "  Creating Python venv at $VENV_DIR..."
  python3 -m venv "$VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
echo "  Using $(python -c 'import sys; print(sys.executable)')"

python -m pip install --quiet --upgrade pip
if [[ -f requirements.txt ]]; then
  python -m pip install --quiet -r requirements.txt
fi

if [[ -f package.json ]]; then
  npm install
fi

if [[ -f Cargo.toml ]] && command -v cargo >/dev/null 2>&1; then
  cargo fetch
elif [[ -f Cargo.toml ]]; then
  echo "  Cargo.toml found but cargo is not installed; skipping cargo fetch."
fi

server_is_ready() {
  curl -sf "$BASE_URL" >/dev/null 2>&1
}

pid_is_running() {
  [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" >/dev/null 2>&1
}

echo "→ Starting dev server..."
if pid_is_running && server_is_ready; then
  echo "  Dev server already running at $BASE_URL."
elif server_is_ready; then
  echo "  A server is already reachable at $BASE_URL; using it for smoke tests."
else
  rm -f "$PID_FILE"
  : > "$LOG_FILE"
  nohup python3 -m http.server "$PORT" --bind "$HOST" > "$LOG_FILE" 2>&1 &
  SERVER_PID=$!
  disown "$SERVER_PID" >/dev/null 2>&1 || true
  echo "$SERVER_PID" > "$PID_FILE"
  echo "  Started fallback static dev server with PID $SERVER_PID."
fi

echo "→ Waiting for server..."
READY=false
for _ in {1..30}; do
  if server_is_ready; then
    READY=true
    break
  fi
  sleep 1
done

if [[ "$READY" != "true" ]]; then
  echo "✗ Environment failed"
  echo "  Server did not become reachable at $BASE_URL. See $LOG_FILE."
  exit 1
fi

echo "→ Running baseline smoke test..."
if ! curl -sf "$BASE_URL/README.md" >/dev/null; then
  echo "✗ Environment failed"
  exit 1
fi

echo "→ Running REST API contract check..."
if ! python3 tools/rest_api_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  REST API contract check failed; run python3 tools/rest_api_check.py for detail."
  exit 1
fi

echo "→ Running WebSocket API contract check..."
if ! python3 tools/websocket_api_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  WebSocket API contract check failed; run python3 tools/websocket_api_check.py for detail."
  exit 1
fi

echo "→ Running CLI contract check..."
if ! python3 tools/cli_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  CLI contract check failed; run python3 tools/cli_check.py for detail."
  exit 1
fi

echo "→ Running brokerage adapter contract check..."
if ! python3 tools/adapter_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Adapter contract check failed; run python3 tools/adapter_check.py for detail."
  exit 1
fi

echo "→ Running data provider contract check..."
if ! python3 tools/data_provider_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Data provider contract check failed; run python3 tools/data_provider_check.py for detail."
  exit 1
fi

echo "→ Running unified historical data contract check..."
if ! python3 tools/historical_data_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Historical data contract check failed; run python3 tools/historical_data_check.py for detail."
  exit 1
fi

echo "→ Running error handling contract check..."
if ! python3 tools/error_handling_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Error handling contract check failed; run python3 tools/error_handling_check.py for detail."
  exit 1
fi

echo "→ Running connectivity contract check..."
if ! python3 tools/connectivity_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Connectivity contract check failed; run python3 tools/connectivity_check.py for detail."
  exit 1
fi

echo "→ Running freshness contract check..."
if ! python3 tools/freshness_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Freshness contract check failed; run python3 tools/freshness_check.py for detail."
  exit 1
fi

echo "→ Running subscription-limit contract check..."
if ! python3 tools/subscription_limit_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Subscription-limit contract check failed; run python3 tools/subscription_limit_check.py for detail."
  exit 1
fi

echo "→ Running ingestion validation contract check..."
if ! python3 tools/ingestion_validation_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Ingestion validation contract check failed; run python3 tools/ingestion_validation_check.py for detail."
  exit 1
fi

echo "→ Running pacing budget contract check..."
if ! python3 tools/pacing_budget_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Pacing budget contract check failed; run python3 tools/pacing_budget_check.py for detail."
  exit 1
fi

echo "→ Running orchestrator lifecycle contract check..."
if ! python3 tools/orchestrator_lifecycle_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Orchestrator lifecycle contract check failed; run python3 tools/orchestrator_lifecycle_check.py for detail."
  exit 1
fi

echo "→ Running orchestrator resource-profile contract check..."
if ! python3 tools/orchestrator_resource_profile_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Orchestrator resource-profile contract check failed; run python3 tools/orchestrator_resource_profile_check.py for detail."
  exit 1
fi

echo "→ Running deployment configuration check..."
if ! python3 tools/deployment_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Deployment check failed; run python3 tools/deployment_check.py for detail."
  exit 1
fi

echo "→ Running configuration system check..."
if ! python3 tools/config_check.py >/dev/null; then
  echo "✗ Environment failed"
  echo "  Configuration check failed; run python3 tools/config_check.py for detail."
  exit 1
fi

echo "✓ Environment ready"
