"""Declarative WebSocket API contract surface for ATP dashboard updates.

This module is the single source of truth for the ATP WebSocket API
described by ``API-3`` in ``feature_list.json`` and traced to
``SRS-UI-001`` through ``SRS-UI-004`` in ``docs/SRS.md`` §7. It declares
event channels, client commands, message types, and the loopback-only
auth model. It does **not** start a WebSocket server: real publishers
land with downstream features (``EXE-1``, ``ORCH-1``, ``MD-1``,
``RESV-1``, ``LOG-1``, ``NOTIF-1``).

The contract surface is introspectable at runtime via
:data:`EVENT_CHANNELS` and :data:`CLIENT_COMMANDS`, and is rendered to
an AsyncAPI 2.6 document by :mod:`atp_ws.asyncapi`. The frozen snapshot
``python/atp_ws/asyncapi.json`` is regenerated by
``python tools/websocket_api_check.py --update``.

SRS trace
---------
``SRS-UI-001`` (live performance dashboard), ``SRS-UI-002`` (active
strategy inventory), ``SRS-UI-003`` (account / Reservoir overview),
``SRS-UI-004`` (backtest history view, served via REST), with
event-level traces to ``SYS-36``..``SYS-39``, ``SYS-39a``, ``SYS-41``,
``SYS-43b``, ``SYS-46``, ``SYS-48``, ``SYS-58``, ``SYS-61``,
``SYS-79``, ``SRS-LOG-001``, ``SRS-NOTIF-001``, ``SRS-RESV-002``,
``NFR-P2`` (5 s refresh ceiling), and ``SRS-SEC-002``
(loopback / single-user policy).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

# --------------------------------------------------------------------------- #
# Auth and bind policy  [SRS-SEC-002]
# --------------------------------------------------------------------------- #


BIND_HOST: str = "127.0.0.1"
"""Default WebSocket bind address.

Per ``SRS-SEC-002`` and the API-3 ``Local single-user deployment
controls`` constraint, the operator WebSocket API binds to loopback (or
RFC 1918) only and does not negotiate authentication tokens or RBAC.
"""

AUTH_MODEL: str = "local-single-user"
"""Auth model identifier.

The platform is single-operator (``StRS`` constraint C-6); the
WebSocket API trusts the local caller. No bearer tokens, sessions, or
RBAC are defined.
"""

WS_PATH: str = "/ws/v1"
"""Versioned WebSocket endpoint path.

Operators connect to ``ws://127.0.0.1:8080{WS_PATH}`` and subscribe to
event channels by name. Channel-level URL routing (e.g. one socket per
channel) is intentionally avoided; the SUBSCRIBE protocol multiplexes
all channels over a single connection.
"""

MAX_REFRESH_SECONDS: int = 5
"""Refresh-cadence ceiling (``NFR-P2``: ≤5 s dashboard refresh).

Channels with periodic publishing must declare a ``refresh_seconds``
between ``0`` (event-driven, no fixed cadence) and this ceiling.
"""


# --------------------------------------------------------------------------- #
# Direction, message types, and channel buckets
# --------------------------------------------------------------------------- #


class Direction(StrEnum):
    """Direction of a WebSocket message relative to the dashboard server.

    Example:
        >>> Direction.SERVER_TO_CLIENT
        <Direction.SERVER_TO_CLIENT: 'SERVER_TO_CLIENT'>
    """

    SERVER_TO_CLIENT = "SERVER_TO_CLIENT"
    CLIENT_TO_SERVER = "CLIENT_TO_SERVER"


class MessageType(StrEnum):
    """Discriminator for the seven framed message types on the socket.

    Event payloads carry ``type=EVENT``; control plane messages carry
    one of the SUBSCRIBE / UNSUBSCRIBE / ACK / ERROR / HEARTBEAT_PING /
    HEARTBEAT_PONG variants.

    Example:
        >>> MessageType.SUBSCRIBE
        <MessageType.SUBSCRIBE: 'SUBSCRIBE'>
    """

    EVENT = "EVENT"
    SUBSCRIBE = "SUBSCRIBE"
    UNSUBSCRIBE = "UNSUBSCRIBE"
    ACK = "ACK"
    ERROR = "ERROR"
    HEARTBEAT_PING = "HEARTBEAT_PING"
    HEARTBEAT_PONG = "HEARTBEAT_PONG"


class Channel(StrEnum):
    """Event channel buckets covered by the WebSocket API contract.

    Each member maps to one of the eight buckets named in ``API-3`` of
    ``feature_list.json``. Every member is covered by at least one entry
    in :data:`EVENT_CHANNELS`; the architecture check enforces this
    superset relation.

    Example:
        >>> Channel.PNL
        <Channel.PNL: 'PNL'>
    """

    PNL = "PNL"
    METRICS = "METRICS"
    ACCOUNT_STATUS = "ACCOUNT_STATUS"
    HEARTBEAT = "HEARTBEAT"
    LOGS = "LOGS"
    ALERTS = "ALERTS"
    RESERVOIR_RANKING = "RESERVOIR_RANKING"
    STRATEGY_STATE = "STRATEGY_STATE"


@dataclass(frozen=True, slots=True)
class EventChannel:
    """Declarative description of one server-to-client event channel.

    The contract is offline: ``payload_fields`` is a placeholder
    field-name tuple for the AsyncAPI snapshot; concrete payload schemas
    arrive with the downstream feature that owns the publisher.

    Attributes:
        name: Channel bucket identifier (see :class:`Channel`).
        summary: One-line human-readable description.
        srs_refs: Tuple of SRS / SyRS / NFR identifiers this channel
            traces to; must contain at least one entry.
        payload_fields: Field names emitted with each event payload.
        refresh_seconds: Maximum interval between publishes for periodic
            channels. ``0`` means event-driven (no fixed cadence).
            ``NFR-P2`` caps this at :data:`MAX_REFRESH_SECONDS`.
        requires_subscription: Whether the client must SUBSCRIBE before
            receiving events on this channel. Defaults to ``True``.

    Example:
        >>> EventChannel(
        ...     name=Channel.HEARTBEAT,
        ...     summary="Market data and broker heartbeat staleness.",
        ...     srs_refs=("SRS-UI-001", "SYS-39"),
        ...     payload_fields=("feed", "staleness_seconds"),
        ...     refresh_seconds=1,
        ... ).requires_subscription
        True
    """

    name: Channel
    summary: str
    srs_refs: tuple[str, ...]
    payload_fields: tuple[str, ...]
    refresh_seconds: int = 5
    requires_subscription: bool = True
    #: JSON types for payload fields whose channel has a REAL publisher, as
    #: ``(field, type)`` pairs; ``"string|null"`` renders as a type union.
    #: Fields left out keep the placeholder ``string`` schema.
    #:
    #: The contract is offline, so an unpublished channel documents its fields
    #: as bare strings and nothing can contradict that. Once a live publisher
    #: exists the placeholder becomes a false statement about the wire: the LOGS
    #: channel carries BOTH log classes, and a system record is validated to have
    #: no ``strategy_id``, so every ordinary system event publishes ``null``
    #: against a schema that says ``string``. A subscriber validating the
    #: documented contract would reject the commonest valid event.
    field_types: tuple[tuple[str, str], ...] = field(default_factory=tuple)
    #: Feature id shipping a real publisher for this channel; ``""`` while
    #: contract-only. A subscriber reads the channel description to decide whether
    #: events will ever arrive; leaving the placeholder on a channel that now
    #: publishes tells them to build a polling fallback they do not need, and the
    #: reverse would have them wait forever on a silent channel. Set it in the
    #: change that starts the publisher — the peer of
    #: :attr:`atp_api.routes.Route.served_by`.
    served_by: str = ""


@dataclass(frozen=True, slots=True)
class ClientCommand:
    """Declarative description of one client-to-server control message.

    Attributes:
        type: Discriminator value (must be one of the CLIENT_TO_SERVER
            members of :class:`MessageType`).
        summary: One-line human-readable description.
        srs_refs: Tuple of SRS / SyRS / NFR identifiers; must be non-empty.
        request_fields: Field names accepted in the command payload.
        response_message: The :class:`MessageType` the server emits in
            response (typically ``ACK`` or ``HEARTBEAT_PONG``).

    Example:
        >>> ClientCommand(
        ...     type=MessageType.SUBSCRIBE,
        ...     summary="Subscribe to one or more channels.",
        ...     srs_refs=("SRS-UI-001",),
        ...     request_fields=("channels",),
        ...     response_message=MessageType.ACK,
        ... ).type
        <MessageType.SUBSCRIBE: 'SUBSCRIBE'>
    """

    type: MessageType
    summary: str
    srs_refs: tuple[str, ...]
    request_fields: tuple[str, ...]
    response_message: MessageType


# --------------------------------------------------------------------------- #
# EVENT_CHANNELS — the API-3 contract (8 channels)
# --------------------------------------------------------------------------- #


EVENT_CHANNELS: tuple[EventChannel, ...] = (
    EventChannel(
        name=Channel.PNL,
        summary="Live profit-and-loss updates per active strategy.",
        srs_refs=("SRS-UI-001", "SYS-36", "NFR-P2"),
        payload_fields=(
            "strategy_id",
            "daily_pnl",
            "cumulative_pnl",
            "unrealized_pnl",
            "as_of",
        ),
        refresh_seconds=1,
    ),
    EventChannel(
        name=Channel.METRICS,
        summary="Live performance metrics including benchmark-relative return.",
        srs_refs=("SRS-UI-001", "SYS-36", "SYS-37"),
        payload_fields=(
            "strategy_id",
            "sharpe",
            "sortino",
            "alpha",
            "beta",
            "max_drawdown",
            "benchmark_return",
            "as_of",
        ),
        refresh_seconds=5,
    ),
    EventChannel(
        name=Channel.ACCOUNT_STATUS,
        summary="IB account equity, P&L, margin, buying power, connection state.",
        srs_refs=("SRS-UI-003", "SYS-43b", "SYS-46"),
        payload_fields=(
            "equity",
            "daily_pnl",
            "cumulative_pnl",
            "margin_usage",
            "buying_power",
            "ib_connection_state",
            "as_of",
        ),
        refresh_seconds=5,
    ),
    EventChannel(
        name=Channel.HEARTBEAT,
        summary="Market data and broker heartbeat staleness watcher.",
        srs_refs=("SRS-UI-001", "SYS-39", "SYS-39a"),
        payload_fields=(
            "feed",
            "last_tick_at",
            "staleness_seconds",
            "is_stale",
        ),
        refresh_seconds=1,
    ),
    EventChannel(
        name=Channel.LOGS,
        summary="System and strategy log events (event-driven, no fixed cadence).",
        srs_refs=("SRS-LOG-001", "SYS-38", "SYS-61"),
        served_by="SRS-LOG-001",
        payload_fields=(
            "timestamp",
            "severity",
            "source",
            "event_type",
            "message",
            "correlation_id",
            # SRS-LOG-001 keeps SYSTEM and STRATEGY logs in separate stores, and
            # the two REST surfaces keep them in separate responses. This ONE
            # channel carries both, so the class discriminant has to travel with
            # every event: without it a subscriber cannot tell a system event
            # from a user-strategy one, and the separation the feature exists to
            # provide would end at the WebSocket boundary.
            "log_class",
            # ``source`` is always the literal "strategy" on a strategy-class
            # event, so without the id every Reservoir strategy's lines look
            # alike on this channel and none can be attributed.
            "strategy_id",
            # Opaque identity of the persisted line: the dashboard merges this
            # channel with a REST poll and must tell one record seen twice from
            # two records that look alike.
            "record_id",
        ),
        # This channel HAS a live publisher (atp_logs_service.LogEventPublisher),
        # and it carries both classes: a SYSTEM event has no strategy id (the
        # record schema forbids one), so the field is legitimately null on the
        # commonest event and the contract has to say so.
        field_types=(("strategy_id", "string|null"),),
        refresh_seconds=0,
    ),
    EventChannel(
        name=Channel.ALERTS,
        summary="Operator alerts with notification delivery status.",
        srs_refs=("SRS-NOTIF-001", "SYS-46", "SYS-58"),
        payload_fields=(
            "alert_id",
            "raised_at",
            "severity",
            "channel",
            "delivery_status",
            "acknowledged",
        ),
        refresh_seconds=0,
    ),
    EventChannel(
        name=Channel.RESERVOIR_RANKING,
        summary="Reservoir strategy ranking with Sharpe, Sortino, and momentum.",
        srs_refs=("SRS-RESV-002", "SYS-48", "SRS-UI-003"),
        payload_fields=(
            "eval_window_days",
            "rankings",
            "sharpe",
            "sortino",
            "momentum_score",
            "as_of",
        ),
        refresh_seconds=5,
    ),
    EventChannel(
        name=Channel.STRATEGY_STATE,
        summary="Active strategy inventory: mode, container status, version.",
        srs_refs=("SRS-UI-002", "SYS-41", "SYS-79"),
        payload_fields=(
            "strategy_id",
            "name",
            "mode",
            "asset_class",
            "container_status",
            "deployment_version_hash",
            "position_count",
            "lifecycle_state",
        ),
        refresh_seconds=5,
    ),
)


# --------------------------------------------------------------------------- #
# CLIENT_COMMANDS — the multiplexed control plane
# --------------------------------------------------------------------------- #


CLIENT_COMMANDS: tuple[ClientCommand, ...] = (
    ClientCommand(
        type=MessageType.SUBSCRIBE,
        summary="Subscribe to one or more event channels on the same socket.",
        srs_refs=("SRS-UI-001", "SRS-UI-002", "SRS-UI-003"),
        request_fields=("channels",),
        response_message=MessageType.ACK,
    ),
    ClientCommand(
        type=MessageType.UNSUBSCRIBE,
        summary="Stop receiving events for one or more previously subscribed channels.",
        srs_refs=("SRS-UI-001",),
        request_fields=("channels",),
        response_message=MessageType.ACK,
    ),
    ClientCommand(
        type=MessageType.HEARTBEAT_PING,
        summary="Connection liveness probe; server replies with HEARTBEAT_PONG.",
        srs_refs=("SYS-39",),
        request_fields=("nonce",),
        response_message=MessageType.HEARTBEAT_PONG,
    ),
)


def channels_by_name(name: Channel) -> tuple[EventChannel, ...]:
    """Return every event channel matching the given :class:`Channel`.

    Example:
        >>> any(ec.name is Channel.PNL for ec in channels_by_name(Channel.PNL))
        True
    """

    return tuple(channel for channel in EVENT_CHANNELS if channel.name is name)


def commands_by_type(message_type: MessageType) -> tuple[ClientCommand, ...]:
    """Return every client command matching the given :class:`MessageType`.

    Example:
        >>> commands_by_type(MessageType.SUBSCRIBE)[0].response_message
        <MessageType.ACK: 'ACK'>
    """

    return tuple(command for command in CLIENT_COMMANDS if command.type is message_type)
