"""L3 contract test for SRS-DATA-015 (schema evolution for stored data entities).

Two layers of evidence:

* :func:`test_check_script_passes` runs ``tools/data015_schema_check.py`` against the real tree, so
  the positive-evidence path stays under CI coverage.
* the **mutation** tests feed the checker deliberately-broken registries and confirm each one FAILS.
  A gate that cannot fail is not a gate: without these, the check could silently degrade to printing
  PASS unconditionally and nothing would notice.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CHECK = ROOT / "tools" / "data015_schema_check.py"
REGISTRY = ROOT / "crates" / "atp-data" / "src" / "schema_registry.rs"
CORPUS = ROOT / "tests" / "fixtures" / "schema_evolution"

pytestmark = [pytest.mark.contract]

_CONTRACT = json.loads((ROOT / "architecture" / "runtime_services.json").read_text())[
    "schema_evolution_contract"
]


def _checker():
    """Import the check script as a module so the mutation tests can call its parts directly."""

    spec = importlib.util.spec_from_file_location("data015_schema_check", CHECK)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module  # dataclasses needs the module registered
    spec.loader.exec_module(module)
    return module


# --------------------------------------------------------------------------- #
# Positive evidence
# --------------------------------------------------------------------------- #


def test_check_script_passes() -> None:
    result = subprocess.run(
        [sys.executable, str(CHECK)], capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, result.stderr
    assert "SRS-DATA-015 SCHEMA-EVOLUTION PASS" in result.stdout


def test_registry_parses_every_declared_entity() -> None:
    module = _checker()
    entities = module.parse_registry(REGISTRY.read_text(encoding="utf-8"))
    assert len(entities) == _CONTRACT["entity_count"]
    assert len({e.entity_id for e in entities}) == len(entities)


def test_contract_block_names_artifacts_that_exist() -> None:
    for key in ("registry_module", "check_script", "cli", "golden_corpus"):
        assert (ROOT / _CONTRACT[key]).exists(), f"{key} points at a missing path"


def test_retrofitted_entities_match_the_registry() -> None:
    module = _checker()
    entities = module.parse_registry(REGISTRY.read_text(encoding="utf-8"))
    retrofitted = {e.entity_id for e in entities if e.legacy_unversioned}
    assert retrofitted == set(_CONTRACT["retrofitted_entities"])


def test_every_retrofitted_entity_has_a_frozen_fixture() -> None:
    module = _checker()
    entities = module.parse_registry(REGISTRY.read_text(encoding="utf-8"))
    for entity in entities:
        if not entity.legacy_unversioned:
            continue
        fixture = module.CORPUS_FIXTURES[entity.entity_id]
        assert (CORPUS / fixture).is_file(), f"{entity.entity_id}: missing {fixture}"


def test_no_legacy_fixture_carries_a_version_key() -> None:
    """The corpus must actually be *legacy*.

    If a "legacy" fixture were regenerated by the current writer it would carry a version key, and
    every no-bulk-migration assertion over it would silently become a round-trip test.
    """

    module = _checker()
    for fixture in module.CORPUS_FIXTURES.values():
        text = (CORPUS / fixture).read_text(encoding="utf-8")
        assert "schema_version" not in text, f"{fixture} is not a pre-versioning payload"
        assert not text.startswith("v1\t"), f"{fixture} is not a pre-versioning payload"


# --------------------------------------------------------------------------- #
# Mutation guards — each broken registry MUST fail the checker
# --------------------------------------------------------------------------- #


def _expect_failure(module, source: str, fragment: str) -> None:
    with pytest.raises(module.SchemaCheckError) as excinfo:
        entities = module.parse_registry(source)
        module.check_registry_invariants(entities)
        module.check_writer_binding(entities)
    assert fragment in str(excinfo.value), f"wrong failure: {excinfo.value}"


def test_mutation_a_dropped_registry_entry_is_caught() -> None:
    """The parse-hole guard: a silently-skipped entry must be a hard failure."""

    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8")
    # Break the LAST entry's terminator, the exact shape that dropped an entry during development.
    broken = source.replace('entity_id: "config-vault-envelope",', 'entity_id_typo: "x",')
    with pytest.raises(module.SchemaCheckError) as excinfo:
        module.parse_registry(broken)
    assert "dropped an entry" in str(excinfo.value) or "missing field" in str(excinfo.value)


def test_mutation_a_wrong_current_version_is_caught() -> None:
    """The registry may not claim a version the writer does not define."""

    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        'entity_id: "market-data-store",\n        owner_srs: "SRS-DATA-016",',
        'entity_id: "market-data-store",\n        owner_srs: "SRS-DATA-016",',
    )
    source = source.replace("current_version: 4,", "current_version: 9,", 1)
    _expect_failure(module, source, "defines SCHEMA_VERSION=4")


def test_mutation_a_bogus_marker_is_caught() -> None:
    """A marker the writer does not contain means the version never reaches the bytes."""

    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        'marker: "ACCESS_JOURNAL_SCHEMA_VERSION",', 'marker: "NOT_A_REAL_CONSTANT",', 1
    )
    _expect_failure(module, source, "does not mention its version marker")


def test_mutation_a_missing_writer_is_caught() -> None:
    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        'writer_path: "python/atp_safety/state.py",',
        'writer_path: "python/atp_safety/does_not_exist.py",',
        1,
    )
    _expect_failure(module, source, "does not exist")


def test_mutation_a_wrong_magic_is_caught() -> None:
    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        'magic: Some("ATP-MARKET-DATA-STORE"),', 'magic: Some("ATP-NOT-THE-REAL-MAGIC"),', 1
    )
    _expect_failure(module, source, "does not contain its declared magic")


def test_mutation_a_duplicate_entity_id_is_caught() -> None:
    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        'entity_id: "order-outbox",', 'entity_id: "access-journal",', 1
    )
    _expect_failure(module, source, "duplicate entity id")


def test_mutation_a_duplicate_magic_is_caught() -> None:
    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        'magic: Some("ATP-BACKTEST-RECORD"),', 'magic: Some("ATP-MARKET-DATA-STORE"),', 1
    )
    _expect_failure(module, source, "share the magic")


def test_mutation_an_inverted_version_range_is_caught() -> None:
    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        "current_version: 4,\n        min_supported_version: 1,",
        "current_version: 1,\n        min_supported_version: 4,",
        1,
    )
    _expect_failure(module, source, "min_supported_version exceeds current_version")


def test_mutation_a_pinned_entity_with_a_range_is_caught() -> None:
    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        """        marker: "SCHEMA_VERSION",
        magic: Some("ATP-BACKTEST-RECORD"),
        current_version: 1,
        min_supported_version: 1,
        posture: EvolutionPosture::Pinned,""",
        """        marker: "SCHEMA_VERSION",
        magic: Some("ATP-BACKTEST-RECORD"),
        current_version: 2,
        min_supported_version: 1,
        posture: EvolutionPosture::Pinned,""",
        1,
    )
    _expect_failure(module, source, "exactly one version")


def test_mutation_a_zero_version_is_caught() -> None:
    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        "current_version: 4,\n        min_supported_version: 1,",
        "current_version: 0,\n        min_supported_version: 0,",
        1,
    )
    _expect_failure(module, source, "versions must be >= 1")


def test_mutation_a_legacy_entity_that_is_not_migrate_on_read_is_caught() -> None:
    """Reading a version-less payload IS an on-read migration; the posture must say so."""

    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8").replace(
        """        posture: EvolutionPosture::MigrateOnRead,
        legacy_unversioned: true,""",
        """        posture: EvolutionPosture::Pinned,
        legacy_unversioned: true,""",
        1,
    )
    _expect_failure(module, source, "posture must be MigrateOnRead")


def test_mutation_an_unregistered_persisted_writer_is_caught(tmp_path: Path) -> None:
    """The totality clause: a new persisted format cannot slip in unregistered.

    Simulated by removing an entity from the registry — the writer it named is then an unregistered
    persistence surface, which is precisely the state a brand-new unversioned format would create.
    """

    module = _checker()
    source = REGISTRY.read_text(encoding="utf-8")
    start = source.find('    SchemaDescriptor {\n        entity_id: "order-outbox",')
    assert start > 0
    end = source.find("    },\n", start) + len("    },\n")
    entities = module.parse_registry(source[:start] + source[end:])
    with pytest.raises(module.SchemaCheckError) as excinfo:
        module.check_totality(entities)
    assert "crates/atp-execution/src/outbox.rs" in str(excinfo.value)
    assert "neither a registered persisted entity" in str(excinfo.value)


def test_mutation_a_stale_allow_list_entry_is_caught(monkeypatch: pytest.MonkeyPatch) -> None:
    """An exemption for a file that persists nothing silently widens the allow-list."""

    module = _checker()
    entities = module.parse_registry(REGISTRY.read_text(encoding="utf-8"))
    monkeypatch.setitem(module.NON_ENTITY_WRITERS, "python/atp_api/openapi.py", "stale")
    with pytest.raises(module.SchemaCheckError) as excinfo:
        module.check_totality(entities)
    assert "no longer persist anything" in str(excinfo.value)


def test_mutation_a_missing_golden_fixture_is_caught(monkeypatch: pytest.MonkeyPatch) -> None:
    module = _checker()
    entities = module.parse_registry(REGISTRY.read_text(encoding="utf-8"))
    monkeypatch.setitem(module.CORPUS_FIXTURES, "access-journal", "not_a_real_fixture.log")
    with pytest.raises(module.SchemaCheckError) as excinfo:
        module.check_corpus(entities)
    assert "missing golden fixture" in str(excinfo.value)


def test_mutation_a_contract_entity_count_drift_is_caught(monkeypatch: pytest.MonkeyPatch) -> None:
    module = _checker()
    entities = module.parse_registry(REGISTRY.read_text(encoding="utf-8"))
    with pytest.raises(module.SchemaCheckError) as excinfo:
        module.check_contract_block(entities[:-1])
    assert "entity_count" in str(excinfo.value)


def test_marker_lookup_does_not_confuse_similar_constant_names() -> None:
    """``SCHEMA_VERSION`` must not resolve to ``MIN_SUPPORTED_SCHEMA_VERSION`` or ``..._V1``.

    Both live in the same files as the real constant, so a sloppy substring match would validate the
    registry against the wrong number and pass while the contract was broken.
    """

    module = _checker()
    source = (
        "pub const MIN_SUPPORTED_SCHEMA_VERSION: i64 = 1;\n"
        "pub const SCHEMA_VERSION: i64 = 4;\n"
        "pub const SCHEMA_VERSION_V1: i64 = 1;\n"
    )
    assert module._declared_constant(source, "SCHEMA_VERSION") == 4
    assert module._declared_constant(source, "MIN_SUPPORTED_SCHEMA_VERSION") == 1
    assert module._declared_constant(source, "SCHEMA_VERSION_V1") == 1
    assert module._declared_constant(source, "NOT_PRESENT") is None
