"""Declarative REST API contract surface for ATP operator workflows.

This module is the single source of truth for the ATP REST API described by
``API-2`` in ``feature_list.json`` and traced to ``SRS-API-001`` in
``docs/SRS.md`` §7. It declares routes, capabilities, and the loopback-only
auth model. It does **not** start an HTTP server: real request handlers will
land with downstream features (``EXE-1``, ``ORCH-1``, ``RESV-1``, ...).

The contract surface is introspectable at runtime via :data:`ROUTES`, and is
turned into an OpenAPI 3.1 document by :mod:`atp_api.openapi`. The frozen
snapshot ``python/atp_api/openapi.json`` is regenerated by
``python tools/rest_api_check.py --update``.

SRS trace
---------
``SRS-API-001`` (REST/CLI/dashboard operator workflows), with route-level
traces to ``SRS-ORCH-004``/``SRS-ORCH-005`` (lifecycle, version, rollback),
``SRS-SAFE-001`` (kill switch), ``SRS-RESV-002``..``SRS-RESV-006`` (Reservoir
ranking, Hot-Swap), ``SRS-BT-001``/``SRS-BT-009`` (backtests),
``SRS-DATA-002`` (watchlist), ``SRS-LOG-001`` (logs), ``SRS-NOTIF-001``
(alerts), ``SRS-SEC-002`` (loopback / RFC 1918 binding).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Tuple


# --------------------------------------------------------------------------- #
# Auth and bind policy  [SRS-SEC-002]
# --------------------------------------------------------------------------- #


BIND_HOST: str = "127.0.0.1"
"""Default REST API bind address.

Per ``SRS-SEC-002`` and the API-2 ``Local single-user deployment controls``
constraint, the operator REST API binds to loopback (or RFC 1918) only and
does not expose authentication tokens or RBAC.
"""

AUTH_MODEL: str = "local-single-user"
"""Auth model identifier.

The platform is single-operator (``StRS`` constraint C-6); the REST API
trusts the local caller. No bearer tokens, sessions, or RBAC are defined.
"""


# --------------------------------------------------------------------------- #
# Method, capability, and route shape
# --------------------------------------------------------------------------- #


class Method(StrEnum):
    """HTTP method for a REST route.

    Example:
        >>> Method.POST
        <Method.POST: 'POST'>
    """

    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"


class Capability(StrEnum):
    """Operator capability buckets covered by the REST API contract.

    Each member maps to one of the eleven buckets named in ``API-2`` of
    ``feature_list.json``. Every member is covered by at least one entry in
    :data:`ROUTES`; the architecture check enforces this superset relation.

    Example:
        >>> Capability.KILL_SWITCH
        <Capability.KILL_SWITCH: 'KILL_SWITCH'>
    """

    STRATEGY_LIFECYCLE = "STRATEGY_LIFECYCLE"
    LIVE_DESIGNATION = "LIVE_DESIGNATION"
    KILL_SWITCH = "KILL_SWITCH"
    HOT_SWAP = "HOT_SWAP"
    BACKTEST_LAUNCH = "BACKTEST_LAUNCH"
    BACKTEST_QUERY = "BACKTEST_QUERY"
    RESERVOIR_RANKING = "RESERVOIR_RANKING"
    WATCHLIST_CONFIG = "WATCHLIST_CONFIG"
    SYSTEM_STATUS = "SYSTEM_STATUS"
    LOGS = "LOGS"
    ALERTS = "ALERTS"


@dataclass(frozen=True, slots=True)
class Route:
    """Declarative description of one REST endpoint.

    The contract is offline: ``request_fields`` and ``response_fields`` are
    placeholder field-name tuples for the OpenAPI snapshot; concrete schemas
    arrive with the downstream feature that implements the handler.

    Attributes:
        method: HTTP method (see :class:`Method`).
        path: URL path beginning with ``/api/v1/``. Path parameters are
            written as ``{name}`` segments.
        capability: Operator capability bucket this route belongs to.
        summary: One-line human-readable description of the endpoint.
        srs_refs: Tuple of SRS / SyRS / NFR identifiers this route traces to;
            must contain at least one entry.
        request_fields: Field names accepted in the request (query for GET,
            body for POST/PUT). Empty tuple is allowed for parameter-less
            endpoints.
        response_fields: Field names returned in the success response body.
        requires_confirmation: Mark routes that perform irreversible actions
            and need a UI two-step confirmation token (modeled here as a
            ``confirm`` query parameter, see ``UI-4``).

    Example:
        >>> Route(
        ...     method=Method.GET,
        ...     path="/api/v1/system/status",
        ...     capability=Capability.SYSTEM_STATUS,
        ...     summary="Return service health and readiness state.",
        ...     srs_refs=("SYS-76",),
        ...     request_fields=(),
        ...     response_fields=("ib_gateway", "ssd", "nas", "services"),
        ... ).method
        <Method.GET: 'GET'>
    """

    method: Method
    path: str
    capability: Capability
    summary: str
    srs_refs: Tuple[str, ...]
    request_fields: Tuple[str, ...] = field(default_factory=tuple)
    response_fields: Tuple[str, ...] = field(default_factory=tuple)
    requires_confirmation: bool = False


# --------------------------------------------------------------------------- #
# ROUTES — the API-2 contract (14 endpoints, 11 capabilities)
# --------------------------------------------------------------------------- #


ROUTES: Tuple[Route, ...] = (
    # ----- Strategy lifecycle  [SRS-ORCH-004, SRS-ORCH-005, SYS-2c, SYS-79, SYS-80]
    Route(
        method=Method.GET,
        path="/api/v1/strategies",
        capability=Capability.STRATEGY_LIFECYCLE,
        summary="List deployed strategies with deployment version and lifecycle state.",
        srs_refs=("SRS-API-001", "SRS-ORCH-004", "SYS-79"),
        request_fields=("status",),
        response_fields=(
            "strategy_id",
            "name",
            "lifecycle_state",
            "deployment_version_hash",
            "deployment_timestamp",
        ),
    ),
    Route(
        method=Method.POST,
        path="/api/v1/strategies/{strategy_id}/lifecycle",
        capability=Capability.STRATEGY_LIFECYCLE,
        summary="Transition a strategy lifecycle (start, stop, restart, rollback).",
        srs_refs=("SRS-ORCH-004", "SRS-ORCH-005", "SYS-2c", "SYS-80"),
        request_fields=("action", "target_version_hash", "confirm"),
        response_fields=("strategy_id", "lifecycle_state", "deployment_version_hash"),
    ),
    # ----- Live designation  [SYS-2c, SYS-2d, SRS-API-001]
    Route(
        method=Method.POST,
        path="/api/v1/strategies/{strategy_id}/promote-live",
        capability=Capability.LIVE_DESIGNATION,
        summary="Designate a strategy as the single live strategy (requires confirmation).",
        srs_refs=("SRS-API-001", "SYS-2c", "SYS-2d"),
        request_fields=("confirm",),
        response_fields=("strategy_id", "is_live", "promoted_at"),
        requires_confirmation=True,
    ),
    # ----- Kill switch  [SRS-SAFE-001, SYS-44a, SYS-44b, NFR-P3]
    Route(
        method=Method.POST,
        path="/api/v1/kill-switch",
        capability=Capability.KILL_SWITCH,
        summary="Activate the QuantConnect Liquidate sequence (cancel, liquidate, halt, disconnect).",
        srs_refs=("SRS-SAFE-001", "SYS-44a", "SYS-44b", "NFR-P3"),
        request_fields=("confirm",),
        response_fields=(
            "activation_id",
            "activated_at",
            "cancelled_orders",
            "liquidation_orders",
            "paper_engines_halted",
            "ib_gateway_disconnected",
        ),
        requires_confirmation=True,
    ),
    # ----- Hot-Swap  [SRS-RESV-003..006, SYS-49a..e]
    Route(
        method=Method.POST,
        path="/api/v1/hot-swap",
        capability=Capability.HOT_SWAP,
        summary="Manually trigger a Reservoir-strategy promotion (demote-then-promote).",
        srs_refs=("SRS-RESV-003", "SRS-RESV-004", "SYS-49a"),
        request_fields=("candidate_strategy_id", "confirm"),
        response_fields=("swap_id", "demotion_state", "promotion_state"),
    ),
    Route(
        method=Method.GET,
        path="/api/v1/hot-swap/status",
        capability=Capability.HOT_SWAP,
        summary="Return current Hot-Swap state, demotion-pending status, and cool-down expiry.",
        srs_refs=("SRS-RESV-005", "SRS-RESV-006", "SYS-49b", "SYS-49e"),
        request_fields=(),
        response_fields=(
            "current_live_strategy_id",
            "demotion_pending",
            "cooldown_expires_at",
            "auto_triggers_enabled",
        ),
    ),
    # ----- Backtest launch  [SRS-BT-001, SYS-14, SYS-43a]
    Route(
        method=Method.POST,
        path="/api/v1/backtests",
        capability=Capability.BACKTEST_LAUNCH,
        summary="Launch a backtest with strategy, date range, parameter, and cost-model overrides.",
        srs_refs=("SRS-BT-001", "SYS-14", "SYS-43a"),
        request_fields=(
            "strategy_id",
            "start_date",
            "end_date",
            "parameter_overrides",
            "cost_model",
            "uploaded_parquet_id",
        ),
        response_fields=("backtest_id", "queued_at"),
    ),
    # ----- Backtest query  [SRS-BT-009, SYS-21, SYS-42]
    Route(
        method=Method.GET,
        path="/api/v1/backtests/{backtest_id}",
        capability=Capability.BACKTEST_QUERY,
        summary="Return persisted backtest results (metrics, trade log, equity curve, benchmark).",
        srs_refs=("SRS-BT-009", "SYS-21", "SYS-42"),
        request_fields=(),
        response_fields=(
            "backtest_id",
            "strategy_id",
            "parameters",
            "metrics",
            "trade_log",
            "equity_curve",
            "benchmark_comparison",
            "deployment_version_hash",
        ),
    ),
    # ----- Reservoir ranking  [SRS-RESV-002, SYS-48]
    Route(
        method=Method.GET,
        path="/api/v1/reservoir/ranking",
        capability=Capability.RESERVOIR_RANKING,
        summary="Rank Reservoir strategies by Sharpe, Sortino, and momentum score.",
        srs_refs=("SRS-RESV-002", "SYS-48"),
        request_fields=("eval_window_days",),
        response_fields=(
            "eval_window_days",
            "rankings",
            "sharpe",
            "sortino",
            "momentum_score",
        ),
    ),
    # ----- Watchlist configuration  [SRS-DATA-002, SYS-22b]
    Route(
        method=Method.GET,
        path="/api/v1/watchlist",
        capability=Capability.WATCHLIST_CONFIG,
        summary="Return the IB minute-bar ingestion watchlist.",
        srs_refs=("SRS-DATA-002", "SYS-22b"),
        request_fields=(),
        response_fields=("symbols", "default_includes_active_strategies"),
    ),
    Route(
        method=Method.PUT,
        path="/api/v1/watchlist",
        capability=Capability.WATCHLIST_CONFIG,
        summary="Replace the IB minute-bar ingestion watchlist.",
        srs_refs=("SRS-DATA-002", "SYS-22b"),
        request_fields=("symbols",),
        response_fields=("symbols", "pacing_budget_remaining"),
    ),
    # ----- System status  [SYS-76, SYS-39, SYS-58]
    Route(
        method=Method.GET,
        path="/api/v1/system/status",
        capability=Capability.SYSTEM_STATUS,
        summary="Return readiness, heartbeat staleness, and resource thresholds.",
        srs_refs=("SYS-76", "SYS-39", "SYS-58"),
        request_fields=(),
        response_fields=(
            "ready",
            "ib_gateway",
            "ssd",
            "nas",
            "services",
            "market_data_heartbeat_age_seconds",
            "resource_alerts",
        ),
    ),
    # ----- Logs  [SRS-LOG-001, SYS-38, SYS-61]
    Route(
        method=Method.GET,
        path="/api/v1/logs",
        capability=Capability.LOGS,
        summary="Query system or strategy logs by severity, source, and time range.",
        srs_refs=("SRS-LOG-001", "SYS-38", "SYS-61"),
        request_fields=(
            "log_class",
            "severity",
            "source",
            "event_type",
            "correlation_id",
            "start_time",
            "end_time",
        ),
        response_fields=(
            "events",
            "timestamp",
            "severity",
            "source",
            "event_type",
            "message",
            "correlation_id",
        ),
    ),
    # ----- Alerts  [SRS-NOTIF-001, SYS-46, SYS-58]
    Route(
        method=Method.GET,
        path="/api/v1/alerts",
        capability=Capability.ALERTS,
        summary="List operator alerts and notification delivery status.",
        srs_refs=("SRS-NOTIF-001", "SYS-46", "SYS-58"),
        request_fields=("acknowledged", "since"),
        response_fields=(
            "alert_id",
            "raised_at",
            "severity",
            "channel",
            "delivery_status",
            "acknowledged",
        ),
    ),
)


def routes_by_capability(capability: Capability) -> Tuple[Route, ...]:
    """Return every route declared for the given capability bucket.

    Example:
        >>> any(r.path == "/api/v1/kill-switch"
        ...     for r in routes_by_capability(Capability.KILL_SWITCH))
        True
    """

    return tuple(route for route in ROUTES if route.capability is capability)
