"""Declarative CLI command surface for ATP operator workflows.

This module is the single source of truth for the ATP command-line
interface described by ``API-4`` in ``feature_list.json`` and traced to
``SRS-API-001`` and ``SRS-SAFE-001`` in ``docs/SRS.md`` §7. It declares
command groups, per-command argument shapes, exit-code semantics, and
the local-shell access policy. It does **not** wire up real handlers:
concrete behaviours land with the downstream features that own each
operator workflow (``EXE-1``, ``ORCH-1``, ``RESV-1``, ``LOG-1``,
``NOTIF-1``).

The contract surface is introspectable at runtime via
:data:`COMMANDS`, and is rendered to a deterministic JSON manual by
:mod:`atp_cli.manual`. The frozen snapshot
``python/atp_cli/manual.json`` is regenerated by
``python tools/cli_check.py --update``.

SRS trace
---------
``SRS-API-001`` (REST/CLI/dashboard operator workflows) and
``SRS-SAFE-001`` (kill switch via dashboard, CLI, REST API), with
group-level traces to ``SRS-ORCH-004``/``SRS-ORCH-005`` (lifecycle,
version, rollback), ``SYS-2c``/``SYS-2d`` (live designation),
``SRS-RESV-003``..``SRS-RESV-006`` (Hot-Swap), ``SYS-76`` (readiness),
``SRS-LOG-001`` (logs), ``SRS-NOTIF-001`` (alerts), and ``SRS-SEC-002``
(loopback / single-user / local-shell policy).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum, StrEnum

# --------------------------------------------------------------------------- #
# Access policy  [SRS-SEC-002, StRS C-6]
# --------------------------------------------------------------------------- #


ACCESS_MODEL: str = "local-shell"
"""CLI access model.

Per ``SRS-SEC-002`` and the API-4 ``Local shell access`` constraint,
the operator CLI runs only under the local operator account on the ATP
host. There is no remote-CLI mode, no auth tokens, and no RBAC.
"""

AUTH_MODEL: str = "local-single-user"
"""Auth model identifier shared with the REST/WebSocket surfaces.

The CLI trusts the local caller (single operator, ``StRS`` C-6) and
authenticates by virtue of OS-level shell access only.
"""

CLI_ENTRY_POINT: str = "atp"
"""Console script name exposed to operators (``atp <group> <command>``)."""

CLI_PROGRAM: str = "python -m atp_cli"
"""Module-invocation form used in tests and examples."""


# --------------------------------------------------------------------------- #
# Groups, exit codes, and command shape
# --------------------------------------------------------------------------- #


class Group(StrEnum):
    """Top-level command groups covered by the CLI contract.

    Each member maps to one of the six capability buckets named in
    ``API-4`` of ``feature_list.json``. Every member is covered by at
    least one entry in :data:`COMMANDS`; the architecture check
    enforces this superset relation.

    Example:
        >>> Group.KILL_SWITCH
        <Group.KILL_SWITCH: 'kill-switch'>
    """

    KILL_SWITCH = "kill-switch"
    STRATEGY = "strategy"
    LIVE = "live"
    HOT_SWAP = "hot-swap"
    READINESS = "readiness"
    ADMIN = "admin"


class ExitCode(IntEnum):
    """Documented exit codes for every CLI command.

    Concrete handlers map outcomes onto these codes; the contract test
    ensures every command's documented exit codes are a subset.

    Example:
        >>> ExitCode.OK
        <ExitCode.OK: 0>
        >>> ExitCode.NOT_IMPLEMENTED
        <ExitCode.NOT_IMPLEMENTED: 64>
    """

    OK = 0
    USAGE_ERROR = 2
    CONFIRMATION_REQUIRED = 3
    NOT_FOUND = 4
    NOT_READY = 5
    TIMEOUT = 6
    NOT_IMPLEMENTED = 64


@dataclass(frozen=True, slots=True)
class Argument:
    """Declarative description of one CLI argument or option.

    Attributes:
        name: Argument identifier; flag arguments are written with
            their ``--`` prefix, positionals without.
        summary: One-line human-readable description.
        required: Whether the argument is required.
        is_flag: Whether the argument is a boolean flag (no value).
        default: Optional default value rendered into the manual.

    Example:
        >>> Argument(
        ...     name="--confirm",
        ...     summary="Two-step confirmation token (SRS-SAFE-001 / UI-4).",
        ...     required=True,
        ...     is_flag=True,
        ... ).is_flag
        True
    """

    name: str
    summary: str
    required: bool = False
    is_flag: bool = False
    default: str | None = None


@dataclass(frozen=True, slots=True)
class Command:
    """Declarative description of one CLI command.

    The contract is offline: argument and exit-code metadata is
    reference material for the manual snapshot; concrete behaviours
    arrive with the downstream feature that owns the workflow.

    Attributes:
        group: Top-level group this command belongs to (see
            :class:`Group`).
        name: Sub-command name as typed after the group; ``""`` for the
            group's default action.
        summary: One-line human-readable description.
        srs_refs: Tuple of SRS / SyRS / NFR identifiers this command
            traces to; must contain at least one entry.
        arguments: Tuple of :class:`Argument` declarations in the order
            they should appear in ``--help`` output.
        exit_codes: Tuple of :class:`ExitCode` values this command may
            return. Must include :attr:`ExitCode.OK`.
        requires_confirmation: Mark commands that perform irreversible
            actions; the runner enforces a ``--confirm`` argument.

    Example:
        >>> Command(
        ...     group=Group.KILL_SWITCH,
        ...     name="activate",
        ...     summary="Activate the QuantConnect Liquidate sequence.",
        ...     srs_refs=("SRS-SAFE-001",),
        ...     arguments=(
        ...         Argument(
        ...             name="--confirm",
        ...             summary="Confirmation token.",
        ...             required=True,
        ...             is_flag=True,
        ...         ),
        ...     ),
        ...     exit_codes=(ExitCode.OK, ExitCode.CONFIRMATION_REQUIRED),
        ...     requires_confirmation=True,
        ... ).requires_confirmation
        True
    """

    group: Group
    name: str
    summary: str
    srs_refs: tuple[str, ...]
    arguments: tuple[Argument, ...] = field(default_factory=tuple)
    exit_codes: tuple[ExitCode, ...] = (ExitCode.OK,)
    requires_confirmation: bool = False

    @property
    def invocation(self) -> str:
        """Canonical ``group sub-command`` invocation string.

        Example:
            >>> Command(
            ...     group=Group.READINESS,
            ...     name="check",
            ...     summary="Show readiness state.",
            ...     srs_refs=("SYS-76",),
            ... ).invocation
            'readiness check'
        """

        if not self.name:
            return self.group.value
        return f"{self.group.value} {self.name}"


# --------------------------------------------------------------------------- #
# COMMANDS — the API-4 contract (6 groups, 18 commands)
# --------------------------------------------------------------------------- #


_CONFIRM = Argument(
    name="--confirm",
    summary="Two-step confirmation token (UI-4 / SRS-SAFE-001).",
    required=True,
    is_flag=True,
)
_JSON = Argument(
    name="--json",
    summary="Emit machine-readable JSON instead of formatted text.",
    is_flag=True,
)


COMMANDS: tuple[Command, ...] = (
    # ----- Kill switch  [SRS-SAFE-001, SYS-44a, SYS-44b, NFR-P3]
    Command(
        group=Group.KILL_SWITCH,
        name="activate",
        summary=(
            "Activate the QuantConnect Liquidate sequence: cancel resting "
            "IB orders, submit market liquidation, halt paper engines, "
            "disconnect IB Gateway."
        ),
        srs_refs=("SRS-SAFE-001", "SYS-44a", "SYS-44b", "NFR-P3"),
        arguments=(_CONFIRM, _JSON),
        exit_codes=(
            ExitCode.OK,
            ExitCode.CONFIRMATION_REQUIRED,
            ExitCode.TIMEOUT,
        ),
        requires_confirmation=True,
    ),
    Command(
        group=Group.KILL_SWITCH,
        name="status",
        summary=(
            "Report current kill-switch state, last activation, and liquidation-order outcomes."
        ),
        srs_refs=("SRS-SAFE-001", "SRS-LOG-001"),
        arguments=(_JSON,),
    ),
    # ----- Strategy management  [SRS-ORCH-004, SRS-ORCH-005, SYS-2c, SYS-79, SYS-80]
    Command(
        group=Group.STRATEGY,
        name="list",
        summary="List deployed strategies with version, mode, and lifecycle state.",
        srs_refs=("SRS-API-001", "SRS-ORCH-004", "SYS-79"),
        arguments=(
            Argument(
                name="--status",
                summary="Filter by lifecycle state (RUNNING, STOPPED, ...).",
            ),
            _JSON,
        ),
    ),
    Command(
        group=Group.STRATEGY,
        name="show",
        summary="Show one strategy's deployment version, container, and live flag.",
        srs_refs=("SRS-ORCH-004", "SYS-79"),
        arguments=(
            Argument(
                name="strategy_id",
                summary="Target strategy identifier.",
                required=True,
            ),
            _JSON,
        ),
        exit_codes=(ExitCode.OK, ExitCode.NOT_FOUND),
    ),
    Command(
        group=Group.STRATEGY,
        name="start",
        summary="Start a deployed strategy (paper mode unless promoted live).",
        srs_refs=("SRS-ORCH-004", "SYS-2c"),
        arguments=(
            Argument(
                name="strategy_id",
                summary="Target strategy identifier.",
                required=True,
            ),
        ),
        exit_codes=(ExitCode.OK, ExitCode.NOT_FOUND, ExitCode.NOT_READY),
    ),
    Command(
        group=Group.STRATEGY,
        name="stop",
        summary="Stop a running strategy and persist its last state.",
        srs_refs=("SRS-ORCH-004", "SYS-2c"),
        arguments=(
            Argument(
                name="strategy_id",
                summary="Target strategy identifier.",
                required=True,
            ),
        ),
        exit_codes=(ExitCode.OK, ExitCode.NOT_FOUND),
    ),
    Command(
        group=Group.STRATEGY,
        name="restart",
        summary="Stop and restart a strategy without changing its deployment version.",
        srs_refs=("SRS-ORCH-004",),
        arguments=(
            Argument(
                name="strategy_id",
                summary="Target strategy identifier.",
                required=True,
            ),
        ),
        exit_codes=(ExitCode.OK, ExitCode.NOT_FOUND),
    ),
    Command(
        group=Group.STRATEGY,
        name="rollback",
        summary="Roll back a strategy to a prior deployment version (live requires --confirm).",
        srs_refs=("SRS-ORCH-005", "SYS-80"),
        arguments=(
            Argument(
                name="strategy_id",
                summary="Target strategy identifier.",
                required=True,
            ),
            Argument(
                name="--target-version-hash",
                summary="Deployment version hash to roll back to.",
                required=True,
            ),
            _CONFIRM,
        ),
        exit_codes=(
            ExitCode.OK,
            ExitCode.NOT_FOUND,
            ExitCode.CONFIRMATION_REQUIRED,
        ),
        requires_confirmation=True,
    ),
    # ----- Live designation  [SRS-API-001, SYS-2c, SYS-2d]
    Command(
        group=Group.LIVE,
        name="promote",
        summary=(
            "Designate a strategy as the single live IB strategy. Enforces "
            "the one-live-strategy invariant; requires --confirm."
        ),
        srs_refs=("SRS-API-001", "SYS-2c", "SYS-2d"),
        arguments=(
            Argument(
                name="strategy_id",
                summary="Strategy to promote to the live IB account.",
                required=True,
            ),
            _CONFIRM,
        ),
        exit_codes=(
            ExitCode.OK,
            ExitCode.NOT_FOUND,
            ExitCode.CONFIRMATION_REQUIRED,
        ),
        requires_confirmation=True,
    ),
    Command(
        group=Group.LIVE,
        name="show",
        summary="Show which strategy currently holds the live IB designation.",
        srs_refs=("SRS-API-001", "SYS-2c"),
        arguments=(_JSON,),
    ),
    # ----- Hot-Swap  [SRS-RESV-003..006, SYS-49a..e]
    Command(
        group=Group.HOT_SWAP,
        name="trigger",
        summary=("Manually demote the live strategy and promote a Reservoir candidate (Hot-Swap)."),
        srs_refs=("SRS-RESV-003", "SRS-RESV-004", "SYS-49a"),
        arguments=(
            Argument(
                name="candidate_strategy_id",
                summary="Reservoir candidate to promote.",
                required=True,
            ),
            _CONFIRM,
        ),
        exit_codes=(
            ExitCode.OK,
            ExitCode.NOT_FOUND,
            ExitCode.CONFIRMATION_REQUIRED,
            ExitCode.TIMEOUT,
        ),
        requires_confirmation=True,
    ),
    Command(
        group=Group.HOT_SWAP,
        name="status",
        summary=(
            "Report Hot-Swap state, current live strategy, demotion-pending, and cool-down expiry."
        ),
        srs_refs=("SRS-RESV-005", "SRS-RESV-006", "SYS-49b", "SYS-49e"),
        arguments=(_JSON,),
    ),
    # ----- Readiness  [SYS-76, SRS-ARCH-005]
    Command(
        group=Group.READINESS,
        name="check",
        summary=(
            "Print readiness state: IB Gateway, SSD, NAS, services, market "
            "data heartbeat staleness, resource alerts."
        ),
        srs_refs=("SYS-76", "SRS-ARCH-005"),
        arguments=(_JSON,),
        exit_codes=(ExitCode.OK, ExitCode.NOT_READY),
    ),
    Command(
        group=Group.READINESS,
        name="wait",
        summary="Block until readiness check passes or timeout elapses.",
        srs_refs=("SYS-76",),
        arguments=(
            Argument(
                name="--timeout",
                summary="Maximum seconds to wait before exiting.",
                default="60",
            ),
        ),
        exit_codes=(ExitCode.OK, ExitCode.TIMEOUT),
    ),
    # ----- Administration  [SRS-LOG-001, SRS-NOTIF-001, SRS-ARCH-005, SYS-58]
    Command(
        group=Group.ADMIN,
        name="logs",
        summary="Tail system or strategy logs filtered by severity, source, time.",
        srs_refs=("SRS-LOG-001", "SYS-38", "SYS-61"),
        arguments=(
            Argument(
                name="--log-class",
                summary="Either 'system' or 'strategy'.",
                default="system",
            ),
            Argument(
                name="--severity",
                summary="Minimum severity (DEBUG, INFO, WARN, ERROR).",
            ),
            Argument(
                name="--source",
                summary="Source component or strategy id.",
            ),
            Argument(
                name="--since",
                summary="ISO-8601 lower bound for event timestamp.",
            ),
            Argument(
                name="--follow",
                summary="Stream events as they arrive instead of returning.",
                is_flag=True,
            ),
            _JSON,
        ),
    ),
    Command(
        group=Group.ADMIN,
        name="alerts",
        summary="List operator alerts and notification delivery status.",
        srs_refs=("SRS-NOTIF-001", "SYS-46", "SYS-58"),
        arguments=(
            Argument(
                name="--acknowledged",
                summary="Filter to only acknowledged or unacknowledged alerts.",
                is_flag=True,
            ),
            Argument(
                name="--since",
                summary="ISO-8601 lower bound for ``raised_at``.",
            ),
            _JSON,
        ),
    ),
    Command(
        group=Group.ADMIN,
        name="config",
        summary=(
            "Show effective ATP configuration with secrets redacted "
            "(SRS-ARCH-005 keys, validators, defaults)."
        ),
        srs_refs=("SRS-ARCH-005",),
        arguments=(_JSON,),
    ),
    Command(
        group=Group.ADMIN,
        name="version",
        summary="Print CLI build version and contract revision.",
        srs_refs=("SRS-API-001",),
        arguments=(_JSON,),
    ),
)


def commands_by_group(group: Group) -> tuple[Command, ...]:
    """Return every command declared for the given group bucket.

    Example:
        >>> any(c.name == "activate"
        ...     for c in commands_by_group(Group.KILL_SWITCH))
        True
    """

    return tuple(command for command in COMMANDS if command.group is group)


def find_command(group: Group, name: str) -> Command | None:
    """Return the unique command matching ``group``/``name`` or ``None``.

    Example:
        >>> find_command(Group.READINESS, "check").summary  # doctest: +ELLIPSIS
        'Print readiness state...'
    """

    for command in COMMANDS:
        if command.group is group and command.name == name:
            return command
    return None
